[versions]
indra = '4.0.0'
jmh = '1.37'
junit = '5.10.0'

[plugins]
indra-publishing = { id = 'net.kyori.indra.publishing', version.ref = 'indra' }
indra-publishing-sonatype = { id = 'net.kyori.indra.publishing.sonatype', version.ref = 'indra' }

jmh = 'me.champeau.jmh:0.7.3'

[libraries]
junit-bom = { module = 'org.junit:junit-bom', version.ref = 'junit' }
junit-jupiter = { module = 'org.junit.jupiter:junit-jupiter' }
junit-platform-launcher = { module = 'org.junit.platform:junit-platform-launcher' }